name: Deploy to Hostinger (FTP)

on:
  push:
    branches: ["master"]   # change en "master" si ton repo utilise master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Déploiement FTP vers Hostinger
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ${{ secrets.FTP_SERVER_DIR }}

          # Important : évite d'envoyer des fichiers inutiles/sensibles
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.env
            **/.DS_Store