name: Deploy to Hostinger (FTP)

on:
  push:
    branches:
      - master   # ou main selon ta branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 82.25.113.190
          username: u366711049
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /home/u366711049/domains/mzewebsite.com/public_html/

          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.env
            **/.DS_Store